In [1]:
# import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier

In [2]:
# import the data
iris = datasets.load_iris()
df = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2     0.0
1                4.9               3.0  ...               0.2     0.0
2                4.7               3.2  ...               0.2     0.0
3                4.6               3.1  ...               0.2     0.0
4                5.0               3.6  ...               0.2     0.0

[5 rows x 5 columns]

where:
1.   **0** is **Iris-setosa**
2.   **1** is **Iris-versicolor**
3.   2 is **Iris-virginica**	




In [3]:
iris_outcome = pd.crosstab(index=iris["target"],  # Make a crosstab
                              columns="count")      # Name the count column

iris_outcome

col_0  count
row_0       
0         50
1         50
2         50

## **ML Phase**

In [5]:
X = df.drop(['target'], axis=1).values
y = df['target'].values

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((100, 4), (100,), (50, 4), (50,))

In [7]:
from sklearn.metrics import confusion_matrix
from sklearn import metrics, preprocessing
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [8]:
DT = DecisionTreeClassifier()
DT.fit(X_train, y_train)

DecisionTreeClassifier()

In [9]:
y_train_pred = DT.predict(X_train)
y_test_pred = DT.predict(X_test)

# Calculate the accuracy
from sklearn.metrics import accuracy_score
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)
conf_matrix = confusion_matrix(y_test, y_test_pred)
class_report = classification_report(y_test, y_test_pred)

print('The training accuracy is', train_accuracy)
print('The test accuracy is', test_accuracy)
print('The confusion matrix is \n', conf_matrix)
print('The classification report is \n', class_report)

The training accuracy is 1.0
The test accuracy is 0.96
The confusion matrix is 
 [[19  0  0]
 [ 0 14  1]
 [ 0  1 15]]
The classification report is 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        19
         1.0       0.93      0.93      0.93        15
         2.0       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50

